name = "protohackers"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Anuj Seth"]
maintainers = ["Anuj Seth <anujseth76@gmail.com>"]
maintainers-logins = ["anuj-seth"]

executables = ["protohackers"]
[[depends-on]]
gnatcoll = "^21.0.0"
